Repository yashksaini-coder/git-graph, pull requests merged in 2025-04, with the labels that each got.

#53 Side Navbar added and made Functional
  eslint.config.mjs
  package-lock.json
  package.json
  src/app/user/[username]/page.tsx
  src/components/shared/CustomizationPanel.tsx
  src/components/ui/sheet.tsx
  src/lib/octokit.ts
Labels: apertre2.0, Hard, Frontend

#55 Feat-UI of the Profile Section (#54)
  package.json
  src/app/api/index.ts
  src/app/user/[username]/page.tsx
  src/components/UserInfo.tsx
  src/components/ui/card.tsx
  src/utils/types.ts
Labels: enhancement, good first issue, apertre2.0, Hard, Frontend, Backend

#59 Sidebar u1 flix
  src/app/user/[username]/page.tsx
  src/components/shared/CustomizationPanel.tsx
Labels: apertre2.0, Medium, Frontend

#67 Fix - bug (#66)
  src/app/user/[username]/page.tsx
Labels: apertre2.0, Medium, Backend

#69 Twittershare
  package-lock.json
  src/app/user/[username]/page.tsx
  src/utils/url.ts
Labels: apertre2.0, Medium, Backend
