Repository yashksaini-coder/git-graph, pull requests merged in 2025-03, with the labels that each got.

#2 Added PR and ISSUE template
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/feature.yml
  .github/PULL_REQUEST_TEMPLATE.md
  package-lock.json
Labels: doc, aperture2.0, Easy

#11 Added background animation and updated header
  package-lock.json
  src/app/layout.tsx
  src/components/header.tsx
  src/components/ui/background.tsx
Labels: enhancement, aperture2.0, Medium, Backend

#13 [Feature] Add Loading animation
  src/app/page.tsx
  src/components/loader.tsx
Labels: enhancement, good first issue, apertre2.0, Medium, Frontend

#15 fixed the footer interaction
  src/components/footer.tsx
Labels: good first issue, apertre2.0, Easy, Frontend

#19 Feature/Dynamic Routing
  src/app/api/index.ts
  src/app/page.tsx
  src/app/username/[username]/page.tsx
  src/hooks/useContibutionsHook.ts
Labels: enhancement, apertre2.0, Backend

#23 fix footer after responsive
  src/components/footer.tsx
Labels: apertre2.0, Easy, Frontend

#25 Create License.md
  License.md
Labels: doc, apertre2.0

#26 Create Security.md
  Security.md
Labels: doc, apertre2.0

#27 Create Code of Conduct.md
  Code of Conduct.md
Labels: doc, apertre2.0

#29 Fix- (#24) Download Graph image for small screen
  src/app/user/[username]/page.tsx
Labels: enhancement, apertre2.0, Hard, Backend

#35 Add Favicon (#16)
  src/app/favicon.ico
Labels: enhancement, apertre2.0, Easy, Frontend

#37 Feature/UserInfo
  package-lock.json
  package.json
  src/app/api/index.ts
  src/app/user/[username]/page.tsx
  src/components/UserInfo.tsx
  src/components/ui/avatar.tsx
  src/components/ui/skeleton.tsx
  src/components/ui/switch.tsx
  src/utils/types.ts
Labels: apertre2.0, Medium, Backend

#40 User Page UI enhanced
  package-lock.json
  src/app/user/[username]/page.tsx
  src/components/header.tsx
  src/lib/octokit.ts
Labels: enhancement, apertre2.0, Medium

#43 Footer and background integration fixed
  src/app/globals.css
  src/app/layout.tsx
  src/app/user/[username]/page.tsx
Labels: apertre2.0, Medium, Backend

#45 Responsiveness Issue Fixed
  src/app/user/[username]/page.tsx
  src/components/header.tsx
Labels: enhancement, apertre2.0, Medium

#49 Feat/add react GitHub calendar
  package-lock.json
  package.json
  src/app/user/[username]/page.tsx
Labels: enhancement, apertre2.0, Medium, Backend

#50 Fix/twitter icon
  package-lock.json
  package.json
  src/components/footer.tsx
Labels: apertre2.0, Medium
